---
abstract: 'Metasyntactic theme with NATO codenames for Soviet-designed equipment'
author:
  - 'Jean Forget <JFORGET@cpan.org>'
build_requires:
  Acme::MetaSyntactic::MultiList: 1
  Test::More: 0
configure_requires:
  Module::Build: 0.33
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MetaSyntactic-soviet
provides:
  Acme::MetaSyntactic::soviet:
    file: lib/Acme/MetaSyntactic/soviet.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
