---
name: Acme-MetaSyntactic-soviet
version: 0.01
author:
  - 'Jean Forget <JFORGET@cpan.org>'
abstract: 'Acme::MetaSyntactic theme, NATO codenames for Soviet equipments'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Acme::MetaSyntactic::MultiList: 0
  Test::More: 0
provides:
  Acme::MetaSyntactic::soviet:
    file: lib/Acme/MetaSyntactic/soviet.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
